### ISSUE TITLE
Allow for automatic location

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/ClimateChangeProjections#1]
When you visit the site the first time (without URL parameters set) the map should use your location to fly to the location, move the cursor, and redraw the visualisation.

- [x] Fly to location
- [ ] Move the cursor/point
- [ ] Redraw visualisation

Awesome work already done by @rtrigoso here: #7.

**Comment by rtrigoso** [comment]
I set a pull request for this issue using geolocation api calls to fix this. please let me know if this works.

**Comment by DavidLemayian** [comment]
Thank you @rtrigoso ! I'll check it out tomorrow.

**Comment by DavidLemayian** [comment]
UX when embedded or link shared breaks with this feature. Going to close for now. 😞
