### ISSUE TITLE
Fail gracefully if map fails to load

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/ClimateChangeProjections#5]
We should check if an error is encountered on map load and submit that feedback to the user.

**Comment by navneetsharmaui** [comment]
@DavidLemayian Can I look into this issue?

**Comment by DavidLemayian** [comment]
Hey @navneetsharmaui . I'm unsure about this issue anymore. The map would fail to load in very special circumstances. Currently #4 kinda solves the UX hurdles. But thank you very much for offering to take a stab at this.
