### ISSUE TITLE
Disable scroll zoom when embedded

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/ClimateChangeProjections#6]
When embedded, we should disable scroll zoom to avoid UX problems in sites.

**Comment by LuKenneth** [comment]
I've opened a pull request for this issue [here](https://github.com/CodeForAfrica/ClimateChangeProjections/pull/8), hope it helps!

**Comment by DavidLemayian** [comment]
I'll check it out tomorrow @LuKenneth . Thank you for sending in the PR.
